[package]
name = "synquid"
version = "0.1.0"
edition = "2024"

[dependencies]
bimap = { version = "0.6.3" }
clap = { version = "4.6.6", features = ["derive"] }
itertools = { version = "0.15.0" }
pretty = { version = "0.12.5" }
z3 = { version = "0.20.2" }

# [lints.rust]
# unsafe_code = "warn"
# missing_docs = "warn"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[lints.clippy]
all = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
# cargo = { level = "warn", priority = -1 }
# restriction = { level = "warn", priority = -1 }

unwrap_used = "warn"

# nursery
use_self = "allow"
option_if_let_else = "allow"

# pedantic
missing_errors_doc = "allow"
missing_panics_doc = "allow"
too_many_lines = "allow"
match_same_arms = "allow"
format_push_string = "allow"
redundant_closure_for_method_calls = "allow"
used_underscore_items = "allow"
manual_let_else = "allow"
map_unwrap_or = "allow"
too_many_arguments = "allow"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "synth"
harness = false
